@echo off
setlocal enabledelayedexpansion

:: ============================================================
:: setup.bat — Singularity Works Integration Setup (Windows)
:: Wires: Forge + LM Studio + Claude Code into one environment
:: ============================================================

echo.
echo  ╔═══════════════════════════════════════════════════════╗
echo  ║   Singularity Works — Integration Setup               ║
echo  ║   Forge + LM Studio + Claude Code                     ║
echo  ╚═══════════════════════════════════════════════════════╝
echo.

set ERRORS=0
set BRIDGE_DIR=%~dp0
set BRIDGE_DIR=%BRIDGE_DIR:~0,-1%

:: ── Step 1: Python ───────────────────────────────────────────
echo [1/6] Checking Python...
python --version >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo       FAIL — Python not found. Install Python 3.10+ from python.org
    set /a ERRORS+=1
    goto :step2
)
for /f "tokens=*" %%v in ('python --version 2^>^&1') do echo       OK — %%v

:: ── Step 2: Claude Code ──────────────────────────────────────
:step2
echo [2/6] Checking Claude Code...
claude --version >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo       FAIL — Claude Code not found.
    echo       Install: npm install -g @anthropic-ai/claude-code
    set /a ERRORS+=1
) else (
    for /f "tokens=*" %%v in ('claude --version 2^>^&1') do echo       OK — %%v
)

:: ── Step 3: curl ─────────────────────────────────────────────
echo [3/6] Checking curl...
curl --version >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo       FAIL — curl not found. Enable in Windows Features or install.
    set /a ERRORS+=1
) else (
    echo       OK — curl available
)

:: ── Step 4: Forge directory ───────────────────────────────────
echo [4/6] Locating Singularity Works Forge...

:: Try common locations
set FORGE_FOUND=0
set CANDIDATE_DIRS=^
    %USERPROFILE%\sw_v19 ^
    %USERPROFILE%\Projects\sw_v19 ^
    C:\Project\sw_v19 ^
    %~dp0..\sw_v19 ^
    %~dp0..\..\sw_v19

for %%d in (%CANDIDATE_DIRS%) do (
    if exist "%%d\singularity_works\orchestration.py" (
        set FORGE_DIR=%%d
        set FORGE_FOUND=1
    )
)

if "%FORGE_FOUND%"=="0" (
    echo       NOT FOUND at standard locations.
    set /p FORGE_DIR="       Enter full path to sw_v19 directory: "
    if not exist "!FORGE_DIR!\singularity_works\orchestration.py" (
        echo       FAIL — forge not found at !FORGE_DIR!
        set /a ERRORS+=1
        set FORGE_DIR=C:\path\to\sw_v19
    ) else (
        echo       OK — Forge found at !FORGE_DIR!
    )
) else (
    echo       OK — Forge found at %FORGE_DIR%
)

:: ── Step 5: LM Studio ────────────────────────────────────────
echo [5/6] Checking LM Studio...
if "%LM_PORT%"=="" set LM_PORT=1234
if "%LM_HOST%"=="" set LM_HOST=127.0.0.1

curl -sf "http://%LM_HOST%:%LM_PORT%/health" >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo       WARN — LM Studio not running at http://%LM_HOST%:%LM_PORT%
    echo       This is OK for setup. Start LM Studio before using lcc.
) else (
    echo       OK — LM Studio online at http://%LM_HOST%:%LM_PORT%
    :: List detected models
    echo       Detecting models...
    python "%BRIDGE_DIR%\forge_bridge.py" status 2>nul | python -c ^
        "import sys,json; d=json.load(sys.stdin); [print('         ' + m) for m in d.get('models',[])]" 2>nul
)

:: ── Step 6: Write environment config ─────────────────────────
echo [6/6] Writing configuration...

set CONFIG_FILE=%BRIDGE_DIR%\sw_env.bat
(
    echo @echo off
    echo :: Singularity Works Environment — auto-generated by setup.bat
    echo :: Source this file or add to your shell profile
    echo.
    echo set FORGE_DIR=%FORGE_DIR%
    echo set LM_HOST=%LM_HOST%
    echo set LM_PORT=%LM_PORT%
    echo set SW_BRIDGE=%BRIDGE_DIR%
    echo.
    echo :: Add lcc to PATH for this session
    echo set PATH=%BRIDGE_DIR%;%%PATH%%
) > "%CONFIG_FILE%"

echo       Config written: %CONFIG_FILE%

:: ── Add lcc to user PATH permanently ─────────────────────────
echo.
echo  Adding %BRIDGE_DIR% to user PATH...
for /f "skip=2 tokens=3*" %%a in ('reg query HKCU\Environment /v PATH 2^>nul') do set CURRENT_PATH=%%a %%b
echo "%CURRENT_PATH%" | find /i "%BRIDGE_DIR%" >nul 2>&1
if %ERRORLEVEL% neq 0 (
    setx PATH "%BRIDGE_DIR%;%CURRENT_PATH%" >nul 2>&1
    echo  PATH updated. Open a new terminal for lcc to be available globally.
) else (
    echo  Already in PATH.
)

:: ── Copy CLAUDE.md to Documents for reference ─────────────────
if exist "%BRIDGE_DIR%\CLAUDE.md" (
    if not exist "%USERPROFILE%\Documents\Singularity-Works" (
        mkdir "%USERPROFILE%\Documents\Singularity-Works" >nul 2>&1
    )
    copy /y "%BRIDGE_DIR%\CLAUDE.md" "%USERPROFILE%\Documents\Singularity-Works\CLAUDE.md" >nul 2>&1
    echo  CLAUDE.md reference copied to Documents\Singularity-Works\
)

:: ── Summary ───────────────────────────────────────────────────
echo.
echo  ══════════════════════════════════════════════════════
if %ERRORS% equ 0 (
    echo   Setup complete. %ERRORS% errors.
    echo.
    echo   Quick start:
    echo     lcc               — show status
    echo     lcc --auto        — launch Claude Code with best model
    echo     lcc --validate file.py   — validate through forge
    echo.
    echo   Per-project setup (run in your project directory^):
    echo     python "%BRIDGE_DIR%\forge_context.py" init --name "YourProject"
    echo     copy "%BRIDGE_DIR%\CLAUDE.md" CLAUDE.md
) else (
    echo   Setup completed with %ERRORS% error(s). Fix the items above.
)
echo  ══════════════════════════════════════════════════════
echo.

:: Source the config for this session
call "%CONFIG_FILE%"
